import React from 'react'
import styles from '../../styles/Home.module.css'
import { demoResume } from '../../lib/data'
import { INTERNALS } from 'next/dist/server/web/spec-extension/request'
import Link from 'next/link'
import Head from 'next/head'

export default function four() {
  return (
    <div className={styles.container}>
        <Head>
        <title>Create Next App</title> 
                <meta name="description" content="Generated by create next app"></meta>
                <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'></link>
        </Head>
        <main className={styles.main}>
            <div className='container w-[210mm] h-[297mm] min-w-[210mm] bg-white text-black'>
                <div className='first w-[85mm] h-[297mm] bg-emerald-700'>
                    
                    <div className='photobg bg-white w-[200px] h-[200px] relative top-16 left-20'></div>
                    <div className='photo'>
                        <img src="https://th.bing.com/th/id/R.3f1e3fb67a36a4f0e88e267a39fc5fe4?rik=SWNFXn5k1gxRFA&riu=http%3a%2f%2fthispix.com%2fwp-content%2fuploads%2f2015%2f06%2fpassport-026.jpg&ehk=MqDfVA9i8hE5HdOOiYBteZYzQTs1TxhQivfpM8mk9EA%3d&risl=&pid=ImgRaw&r=0" className='w-[200px] h-[200px] relative'></img>
                    </div>
                    
                </div>
                <div className='second'>

                </div>
            </div>
        </main>
    </div>
  )
}
