import React from "react";
import styles from "../../styles/Home.module.css";
import { demoResume } from "../../lib/data";
import { INTERNALS } from "next/dist/server/web/spec-extension/request";
import Head from "next/head";
import Link from "next/link";

export default function three() {
  const resume = demoResume();
  return (
    <div className="">
      <Head>
        <title>Create next app</title>
        <meta name="description" content="generated by create next app"></meta>
        <link
          href="https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css"
          rel="stylesheet"
        ></link>
      </Head>
      <main className="flex justify-center">
        <div className=" w-[210mm] h-[297mm] min-w-[210mm] bg-white text-black">
          <div className="first">
            <div className="w-[150mm] h-[130px] bg-black ml-[60mm] mt-[50px]">
              <div className="name text-white bg-black">
                <h1 className="pl-[100px] pt-[20px] text-lg font-bold text-white bg-black">
                  {resume.personal.firstName}
                  <span className="pl-4 font-medium text-white bg-black">
                    {resume.personal.lastName}
                  </span>
                </h1>
                <h2 className="text-white pl-[100px] pt-2 text-base bg-black">
                  {resume.personal.role}
                </h2>
              </div>
              <div className="pl-16 pt-2">
                <div className="social pl-10 pt-1 flex relative">
                  {resume.social.map((item) => (
                    <div className="pr-2">
                      <span>
                        <Link href={item.url}>
                          <img
                            src={
                              "https://www." + item.network + ".com/favicon.ico"
                            }
                            className="w-5 grayscale-[40%]"
                          ></img>
                        </Link>
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
            <div className="photo relative top-[-170px] left-[80px]">
              <img
                src="https://th.bing.com/th/id/R.3f1e3fb67a36a4f0e88e267a39fc5fe4?rik=SWNFXn5k1gxRFA&riu=http%3a%2f%2fthispix.com%2fwp-content%2fuploads%2f2015%2f06%2fpassport-026.jpg&ehk=MqDfVA9i8hE5HdOOiYBteZYzQTs1TxhQivfpM8mk9EA%3d&risl=&pid=ImgRaw&r=0"
                className="w-[200px] h-[200px] rounded-full border-[12px] border-black"
              ></img>
            </div>
            <div className="career-objective w-[180mm] relative top-[-170px] left-[80px] text-sm">
              {resume.objective}
            </div>
          </div>
          <div className="second relative top-[-170px] flex">
            <div className="third  w-[320px]">
              <div className="contact">
                <div className="dob pl-8 pt-5">
                  <i className="bx bxs-calendar pr-4 text-lg"></i>
                  <span className="text-sm relative bottom-[3px]">
                    {resume.personal.dob}
                  </span>
                </div>
                <div className="phone pl-8 pt-1">
                  <i className="bx bxs-phone pr-4 text-lg"></i>
                  <span className="text-sm relative bottom-1">
                    {resume.personal.phone}
                  </span>
                </div>
                <div className="mail pl-8 pt-1">
                  <i className="bx bxs-envelope pr-4 text-lg"></i>
                  <span className="text-sm relative bottom-1">
                    {resume.personal.email}
                  </span>
                </div>
              </div>
              <div className="education">
                <div className="pb-2">
                  <h2 className="text-center text-base font-serif font-semibold pt-3 pb-1 border-b-[4px] border-black">
                    E D U C A T I O N
                  </h2>
                  <div className="py-2">
                  {resume.education.map((item) => (
                    <p className="pl-5 pr-5 pt-2 text-sm">
                      <span className="font-medium">{item.institution}</span> in{" "}
                      <span className="font-medium">
                        {item.fieldOfStudy}
                        <br />({item.startDate} to {item.endDate})
                      </span>
                      <br />
                      <i className="bx bxs-graduation"></i> {item.typeOfDegree}{" "}
                      in {item.fieldOfStudy} ({item.gpa})
                    </p>
                  ))}
                  </div>
                </div>
              </div>
              <div className="certifications">
                <div className="pb-2">
                  <h2 className="text-center text-base font-serif font-semibold border-b-[4px] border-black pt-2 pb-1">
                    C E R T I F I C A T I O N S
                  </h2>
                  <div className="py-2">
                  {resume.certifications.map((item) => (
                    <p className="pl-5 pr-2 pt-2 text-sm">
                      <i className="bx bxs-square text-xs pr-3"></i>
                      {item.title} from {item.issuer}
                    </p>
                  ))}
                  </div>
                </div>
              </div>
              <div className="skills">
                <div className="">
                  <h2 className="text-center text-base font-serif font-semibold pt-1 pb-1 border-b-[4px] border-black">
                    S K I L L S
                  </h2>
                  <div className="pt-1 pl-5 py-2">
                    {resume.skills.map((item) => (
                      <span className="pr-2 text-sm">{item.name} </span>
                    ))}
                  </div>
                </div>
              </div>
              <div className="hobbies">
                <div className=" pb-5">
                  <h2 className="text-center text-base font-serif font-semibold pt-1 pb-1 border-b-[4px] border-black">
                    H O B B I E S
                  </h2>
                  <div className="pt-1 pl-5">
                    {resume.hobbies.map((item) => (
                      <span className="pr-2 text-sm">{item.name} </span>
                    ))}
                  </div>
                </div>
              </div>
            </div>
            <div className="fourth w-[500px]">
              <div className="experience">
                <h2 className="text-center text-base font-serif font-semibold pt-5 border-b-[4px] mx-1 border-black">
                  E X P E R I E N C E
                </h2>
                <div className="pb-1 py-2">
                  {resume.work.map((item) => (
                    <p className="pl-10 pr-5 pt-1 text-sm">
                      <span className="font-medium  pr-3">
                        {item.designation} in {item.company}
                      </span>
                      <br></br>({item.from} to {item.to})<br />
                      <Link href={item.website}>{item.website}</Link>
                      <br></br>
                      <span className="text-sm">{item.summary.data}</span>
                    </p>
                  ))}
                </div>
              </div>
              <div className="projects">
                <h2 className="text-center text-base font-serif font-semibold pt-3 border-b-[4px] mx-1 border-black">
                  P R O J E C T S
                </h2>
                <div className="py-2">
                  {resume.projects.map((item) => (
                    <p className="pl-10 pr-5 text-sm pt-1">
                      <span className="font-medium pr-3">{item.name}</span> (
                      {item.from} to {item.to})<br />
                      <Link href={item.website}>{item.website}</Link>
                      <br></br>
                      <span className="">{item.summary.data}</span>
                    </p>
                  ))}
                </div>
              </div>
              <div className="awards">
                <h2 className="text-center text-base font-serif font-semibold pt-1 border-b-[4px] mx-1 border-black">
                  A W A R D S
                </h2>
                {resume.awards.map((item) => (
                  <p className="pl-10 pr-5 py-2 text-sm">
                    <i className="bx bxs-award pr-1"></i>
                    <span className="font-medium">{item.name}</span> from{" "}
                    {item.awarder}
                  </p>
                ))}
              </div>
              <div className="languages">
                <div className="">
                  <h2 className="text-center text-base font-serif font-semibold pt-1 pb-1 border-b-[4px] mx-1 border-black">
                    L A N G U A G E S
                  </h2>
                  <div className="pt-1 pl-10">
                    {resume.languages.map((item) => (
                      <span className="text-sm pr-2">{item.name} </span>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
